### ISSUE TITLE
Avoid loading fonts from googleapis

### ISSUE THREAD

**Issue by ChrisZou** [elm-lang/elm-reactor#216]
Hi, I really like Elm and spent a lot of time on it. Today, I found that when I use the Elm reactor(version 0.18.0) to serve my Elm file, the generated html would try to load some fonts from googleapis.com

```css
@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro);
html, head, body {
  margin: 0;
  height: 100%;
}
```

This would make the page take a long time to load in some areas like China, since we cannot connect to most of the google sites(including googleapis.com). So would you please remove the fonts loading from googleapis or make it async so that it would not block the content loading?
Thank you for the wonderful job!
